// Code generated by protoc-gen-go. DO NOT EDIT.
// source: global.proto

package konlpy_v0alpha

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Option struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                bool     `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{0}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Option) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type StringRequest struct {
	Payload              string    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Options              []*Option `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StringRequest) Reset()         { *m = StringRequest{} }
func (m *StringRequest) String() string { return proto.CompactTextString(m) }
func (*StringRequest) ProtoMessage()    {}
func (*StringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{1}
}

func (m *StringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringRequest.Unmarshal(m, b)
}
func (m *StringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringRequest.Marshal(b, m, deterministic)
}
func (m *StringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringRequest.Merge(m, src)
}
func (m *StringRequest) XXX_Size() int {
	return xxx_messageInfo_StringRequest.Size(m)
}
func (m *StringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StringRequest proto.InternalMessageInfo

func (m *StringRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *StringRequest) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type TupleArrayResponse struct {
	Results              []*TupleArrayResponse_Tuple `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Options              []*Option                   `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *TupleArrayResponse) Reset()         { *m = TupleArrayResponse{} }
func (m *TupleArrayResponse) String() string { return proto.CompactTextString(m) }
func (*TupleArrayResponse) ProtoMessage()    {}
func (*TupleArrayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{2}
}

func (m *TupleArrayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TupleArrayResponse.Unmarshal(m, b)
}
func (m *TupleArrayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TupleArrayResponse.Marshal(b, m, deterministic)
}
func (m *TupleArrayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TupleArrayResponse.Merge(m, src)
}
func (m *TupleArrayResponse) XXX_Size() int {
	return xxx_messageInfo_TupleArrayResponse.Size(m)
}
func (m *TupleArrayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TupleArrayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TupleArrayResponse proto.InternalMessageInfo

func (m *TupleArrayResponse) GetResults() []*TupleArrayResponse_Tuple {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *TupleArrayResponse) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type TupleArrayResponse_Tuple struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TupleArrayResponse_Tuple) Reset()         { *m = TupleArrayResponse_Tuple{} }
func (m *TupleArrayResponse_Tuple) String() string { return proto.CompactTextString(m) }
func (*TupleArrayResponse_Tuple) ProtoMessage()    {}
func (*TupleArrayResponse_Tuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{2, 0}
}

func (m *TupleArrayResponse_Tuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TupleArrayResponse_Tuple.Unmarshal(m, b)
}
func (m *TupleArrayResponse_Tuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TupleArrayResponse_Tuple.Marshal(b, m, deterministic)
}
func (m *TupleArrayResponse_Tuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TupleArrayResponse_Tuple.Merge(m, src)
}
func (m *TupleArrayResponse_Tuple) XXX_Size() int {
	return xxx_messageInfo_TupleArrayResponse_Tuple.Size(m)
}
func (m *TupleArrayResponse_Tuple) XXX_DiscardUnknown() {
	xxx_messageInfo_TupleArrayResponse_Tuple.DiscardUnknown(m)
}

var xxx_messageInfo_TupleArrayResponse_Tuple proto.InternalMessageInfo

func (m *TupleArrayResponse_Tuple) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *TupleArrayResponse_Tuple) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type StringArrayResponse struct {
	Results              []string  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Options              []*Option `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StringArrayResponse) Reset()         { *m = StringArrayResponse{} }
func (m *StringArrayResponse) String() string { return proto.CompactTextString(m) }
func (*StringArrayResponse) ProtoMessage()    {}
func (*StringArrayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{3}
}

func (m *StringArrayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringArrayResponse.Unmarshal(m, b)
}
func (m *StringArrayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringArrayResponse.Marshal(b, m, deterministic)
}
func (m *StringArrayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringArrayResponse.Merge(m, src)
}
func (m *StringArrayResponse) XXX_Size() int {
	return xxx_messageInfo_StringArrayResponse.Size(m)
}
func (m *StringArrayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StringArrayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StringArrayResponse proto.InternalMessageInfo

func (m *StringArrayResponse) GetResults() []string {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *StringArrayResponse) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*Option)(nil), "konlpy.v0alpha.Option")
	proto.RegisterType((*StringRequest)(nil), "konlpy.v0alpha.StringRequest")
	proto.RegisterType((*TupleArrayResponse)(nil), "konlpy.v0alpha.TupleArrayResponse")
	proto.RegisterType((*TupleArrayResponse_Tuple)(nil), "konlpy.v0alpha.TupleArrayResponse.Tuple")
	proto.RegisterType((*StringArrayResponse)(nil), "konlpy.v0alpha.StringArrayResponse")
}

func init() { proto.RegisterFile("global.proto", fileDescriptor_4baa8fc7dedf329e) }

var fileDescriptor_4baa8fc7dedf329e = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x25, 0xbb, 0xec, 0xae, 0x1d, 0x3f, 0x90, 0x28, 0x12, 0x3c, 0x95, 0x9e, 0x7a, 0x2a, 0xc5,
	0xfd, 0x05, 0xfa, 0x07, 0x84, 0xe8, 0xcd, 0xd3, 0x2c, 0x0e, 0x75, 0x69, 0xe8, 0xc4, 0x24, 0x5d,
	0xc9, 0xaf, 0xf3, 0xaf, 0x49, 0xd3, 0xad, 0x50, 0x3d, 0x89, 0xb7, 0x79, 0x21, 0xef, 0xcd, 0x7b,
	0x6f, 0xe0, 0xac, 0x31, 0xbc, 0x43, 0x53, 0x59, 0xc7, 0x81, 0xe5, 0x45, 0xcb, 0x9d, 0xb1, 0xb1,
	0x3a, 0xd4, 0x68, 0xec, 0x1b, 0x16, 0x35, 0xac, 0x1f, 0x6d, 0xd8, 0x73, 0x27, 0x2f, 0x61, 0xd9,
	0x52, 0x54, 0x22, 0x17, 0x65, 0xa6, 0x87, 0x51, 0x5e, 0xc3, 0xea, 0x80, 0xa6, 0x27, 0xb5, 0xc8,
	0x45, 0x79, 0xa2, 0x47, 0x50, 0xbc, 0xc0, 0xf9, 0x53, 0x70, 0xfb, 0xae, 0xd1, 0xf4, 0xde, 0x93,
	0x0f, 0x52, 0xc1, 0xc6, 0x62, 0x34, 0x8c, 0xaf, 0x47, 0xf2, 0x04, 0x65, 0x0d, 0x1b, 0x4e, 0xe2,
	0x5e, 0x2d, 0xf2, 0x65, 0x79, 0x7a, 0x77, 0x53, 0xcd, 0xd7, 0x57, 0xe3, 0x6e, 0x3d, 0x7d, 0x2b,
	0x3e, 0x05, 0xc8, 0xe7, 0xde, 0x1a, 0xba, 0x77, 0x0e, 0xa3, 0x26, 0x6f, 0xb9, 0xf3, 0x24, 0x1f,
	0x60, 0xe3, 0xc8, 0xf7, 0x26, 0x78, 0x25, 0x92, 0x50, 0xf9, 0x53, 0xe8, 0x37, 0x69, 0x7c, 0xd2,
	0x13, 0xf1, 0xef, 0x66, 0x6e, 0xb7, 0xb0, 0x4a, 0x1a, 0x43, 0xc2, 0x96, 0xe2, 0x07, 0xbb, 0xef,
	0x84, 0x47, 0x38, 0x94, 0x16, 0xb0, 0x49, 0x05, 0x65, 0x7a, 0x18, 0x0b, 0x84, 0xab, 0xb1, 0x9e,
	0x79, 0x02, 0x35, 0x4f, 0x90, 0xfd, 0xc3, 0xd7, 0x6e, 0x9d, 0x4e, 0xb9, 0xfd, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x4e, 0xee, 0x96, 0x7d, 0xda, 0x01, 0x00, 0x00,
}
